### ISSUE TITLE
Can't paste into signature reader

### ISSUE THREAD

**Issue by sikxshot** [exodus4d/pathfinder#694] opened 2018-09-27 20:43 UTC
Hi on the public server, since the last update I can't paste into the signature reader. The dialog box opens but the "update signatures" button does nothing. I've created a new map but does not help.

**Comment by mrurb** [comment] 2018-09-27 21:11
Duplicate of #691

**Comment by exodus4d** [comment] 2018-09-27 22:30
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*

**Closed by exodus4d** 2018-09-27 22:30 UTC
Labels: duplicate
