### ISSUE TITLE
Updates of systems position changes don't propagate through clients.

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#505] opened 2017-07-09 13:43 UTC
I noticed that after last update from 1.2.1 to 1.2.3 we have very often a problem with propagation of changes made to the map. Updating signatures works quite fine but when people move systems around the map it often looks like changes do not propagate to other clients or even stay local for the current tab in browser. If refreshed it changes back to some old position.
Very often there is a situation when few people have few different views of the map. Then they try to move systems to make the map readable and suddenly the changed system propagates. So the new change is on top of old systems position leading to a chaos.

Screenshots below show the same map from three characters. One on different computer, two others on the same browser. In that particular case only the movement of the system where character "Oposka" is was propagating. So we were bouncing it back and forth because it was getting in a way with other systems on other computers.

[![Screenshot from Gyazo](https://gyazo.com/c29d43d5bfc554a4c383ce51d40e5627/raw)](https://gyazo.com/c29d43d5bfc554a4c383ce51d40e5627)

[![Screenshot from Gyazo](https://gyazo.com/1bc596c8efbf9d7032450640d7c16b4c/raw)](https://gyazo.com/1bc596c8efbf9d7032450640d7c16b4c)

[![Screenshot from Gyazo](https://gyazo.com/2acb1bb4bf622e35d04089004b85cc3a/raw)](https://gyazo.com/2acb1bb4bf622e35d04089004b85cc3a)

**Comment by maurerit** [comment] 2017-07-09 17:33
https://github.com/exodus4d/pathfinder/pull/506 should fix this issue

**Comment by exodus4d** [comment] 2017-07-16 15:35
@maurerit Thanks for the fix. I´m unable to reproduce this error. However I´ll check your PR. 
It would be awesome if you could provide a screenshot of the error (browser dev-tools) and the backtrace, the next time. :) 

There could be multiple other problems that could lead to problems with map sync as well.

**Comment by WildStrawberryEVE** [comment] 2017-07-19 10:34
I think I have it reproducible.
For a long time I just could not spot the moment when the map goes out of sync. Today - with 3 characters on three tabs I spotted the pattern.

It happened when I selected more systems and dragged them around the map.
From all selected systems, only the one I was dragging was later synced with others. All remaining selected systems were moved only on that one tab which done the move. After refreshing page everything except that one system was rolled back for that character.

@maurerit - is your proposed commit fixing that particular issue?

**Comment by exodus4d** [comment] 2017-07-28 19:48
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*

**Closed by exodus4d** 2017-07-28 19:48 UTC
Labels: major bug, not reproducible
