### ISSUE TITLE
PHP7.2: session_start(): Failed to read session data: user

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#595] opened 2018-03-19 07:36 UTC
Under PHP7.2 running off the top of develop, the following line generates an error:

https://github.com/exodus4d/pathfinder/blob/23758f235cff287f18933b47475547e7ccaf93a0/app/main/controller/controller.php#L412

```[18-Mar-2018 21:56:48 UTC] session_start(): Failed to read session data: user (path: /var/lib/php/sessions)
[18-Mar-2018 21:56:48 UTC] [app/main/controller/controller.php:412] Base->exists()```

**Comment by exodus4d** [comment] 2018-03-19 18:33
Interesting, I don´t have the problem on my local development environment (PHP 7.2). Do you have some more information how to reproduce, and/or the full error log entry (stacktrace)?

**Comment by atkinsj** [comment] 2018-03-20 08:31
I can't find a trend personally:

`[20-Mar-2018 08:15:46 UTC] HTTP 403 (POST /api/user/logout)
[20-Mar-2018 08:15:46 UTC] [app/lib/db/sql/session.php:77] Base->error()
[20-Mar-2018 08:15:46 UTC] [app/main/controller/controller.php:457] Base->get()
[20-Mar-2018 08:15:46 UTC] [app/main/controller/api/user.php:208] Controller\Controller->logoutCharacter()
[20-Mar-2018 08:15:46 UTC] [index.php:23] Base->run()
[20-Mar-2018 08:15:46 UTC] session_set_save_handler(): Cannot change save handler when session is active
[20-Mar-2018 08:15:46 UTC] [app/lib/db/sql/session.php:202] session_set_save_handler()
[20-Mar-2018 08:15:46 UTC] [app/main/controller/controller.php:140] DB\SQL\Session->__construct()
[20-Mar-2018 08:15:46 UTC] [app/main/controller/controller.php:73] Controller\Controller->initSession()
[20-Mar-2018 08:15:46 UTC] [app/lib/db/sql/session.php:77] Base->error()
[20-Mar-2018 08:15:46 UTC] [app/main/controller/controller.php:457] Base->get()
[20-Mar-2018 08:15:46 UTC] [app/main/controller/api/user.php:208] Controller\Controller->logoutCharacter()
[20-Mar-2018 08:15:46 UTC] [index.php:23] Base->run()
[20-Mar-2018 08:15:46 UTC] session_start(): Failed to read session data: user (path: /var/lib/php/sessions)
[20-Mar-2018 08:15:46 UTC] [app/main/controller/controller.php:457] Base->get()
[20-Mar-2018 08:15:46 UTC] [app/main/controller/api/user.php:208] Controller\Controller->logoutCharacter()
[20-Mar-2018 08:15:46 UTC] [index.php:23] Base->run()`

**Comment by atkinsj** [comment] 2018-03-20 09:07
So I think this is happening with the nginx environment configuration; I noticed error.log was spitting out pathfinder/pathfinder/pathfinder DB connection errors. Fixed environment.ini and I'm no longer getting errors.

**Comment by atkinsj** [comment] 2018-03-22 06:49
Nope -- still happening.

**Comment by dkrotil** [comment] 2018-03-22 18:14
Any additional info ? New install, upgraded from 7.1 , it was working , etc .

**Comment by atkinsj** [comment] 2018-03-24 01:59
Happened on the upgrade to 1.3.1 to 1.3.3, no other system changes etc.

**Comment by atkinsj** [comment] 2018-03-27 02:39
So I've tracked this down to a specific instance: it only happens when you re-visit Pathfinder after being away for some time (i.e., your session has expired). Is there something keyed off a cookie or something that could cause it to read a session variable that has expired?

**Comment by atkinsj** [comment] 2018-04-03 01:08
@exodus4d FYI, I think this is fixed in upstream F3. You might need an update:

https://github.com/bcosca/fatfree-core/commit/4f50cd0aa0c8de46968258f90d4d280c355c7029 (ref: https://groups.google.com/forum/#!topic/f3-framework/WfCJpW479Vw).

**Comment by exodus4d** [comment] 2018-04-06 22:08
@atkinsj This fix is already included into the pathfinder repo a while ago. But good point with the SQL Sessions. I have set up _Redis_ as Session handler for all my instances maybe therefore I never ran into that issue... ? Could you fixed the problem on your installation?

**Comment by atkinsj** [comment] 2018-04-06 23:05
Unfortunately this is with the Redis cache.

**Comment by exodus4d** [comment] 2018-04-07 12:09
@atkinsj Yould you compair your php.ini setting for Sessions with those from my installation?

**Comment by exodus4d** [comment] 2018-04-07 13:30
I got some feedback from the F3 devs. They fixed something in https://github.com/bcosca/fatfree-core/issues/238#issuecomment-378516436 Ill check if this fix is relevant for your problem and/or if it is already part of _Pathfinder_ a new F3 release will be stashed "over the weekend".

**Comment by dkrotil** [comment] 2018-04-25 08:13
Any update on this ? Thinking about upgrade of PHP to 7.2 .

**Comment by exodus4d** [comment] 2018-06-09 09:31
@dkrotil I can´t see any PHP 7.2 related issues with the sessions :( I have my _production_, _develop_, and _local dev_ environment on 7.2 for 2 month now, and cant see any problems :(

**Comment by exodus4d** [comment] 2018-06-22 18:07
When `mysql` Sessions are used (`pconfig.ini` -> `SESSION_CACHE =   mysql`) I got the error @atkinsj  mentioned. Unfortunately  I was unable to reproduce, but from the logs I saw I made some changes. Feel free to replace those lines and let me know if this helps 38ceb92 :
File: `app/main/controller/controller.php` 

```
[22-Jun-2018 13:33:33 UTC] PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '271683000370650e53eaebb466051ba7' for key 'PRIMARY'
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/base.php:2219] Base->error()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/sql.php:226] PDOStatement->execute()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/sql/mapper.php:439] DB\SQL->exec()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/cursor.php:245] DB\SQL\Mapper->insert()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/sql/session.php:95] DB\Cursor->save()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/base.php:2091] session_commit()
[22-Jun-2018 13:33:33 UTC] PHP Warning:  session_set_save_handler(): Cannot change save handler when session is active in G:\webpages\pathfinder\app\lib\db\sql\session.php on line 202
[22-Jun-2018 13:33:33 UTC] PHP Stack trace:
[22-Jun-2018 13:33:33 UTC] PHP   1. Base->unload() G:\webpages\pathfinder\app\lib\base.php:0
[22-Jun-2018 13:33:33 UTC] PHP   2. session_commit() G:\webpages\pathfinder\app\lib\base.php:2091
[22-Jun-2018 13:33:33 UTC] PHP   3. DB\SQL\Session->write() G:\webpages\pathfinder\app\lib\base.php:2091
[22-Jun-2018 13:33:33 UTC] PHP   4. DB\SQL\Session->save() G:\webpages\pathfinder\app\lib\db\sql\session.php:95
[22-Jun-2018 13:33:33 UTC] PHP   5. DB\SQL\Session->insert() G:\webpages\pathfinder\app\lib\db\cursor.php:245
[22-Jun-2018 13:33:33 UTC] PHP   6. DB\SQL->exec() G:\webpages\pathfinder\app\lib\db\sql\mapper.php:439
[22-Jun-2018 13:33:33 UTC] PHP   7. PDOStatement->execute() G:\webpages\pathfinder\app\lib\db\sql.php:226
[22-Jun-2018 13:33:33 UTC] PHP   8. Base->{closure:G:\webpages\pathfinder\app\lib\base.php:2217-2220}() G:\webpages\pathfinder\app\lib\db\sql.php:226
[22-Jun-2018 13:33:33 UTC] PHP   9. Base->error() G:\webpages\pathfinder\app\lib\base.php:2219
[22-Jun-2018 13:33:33 UTC] PHP  10. Base->call() G:\webpages\pathfinder\app\lib\base.php:1270
[22-Jun-2018 13:33:33 UTC] PHP  11. Controller\Controller->beforeroute() G:\webpages\pathfinder\app\lib\base.php:1831
[22-Jun-2018 13:33:33 UTC] PHP  12. Controller\Controller->initSession() G:\webpages\pathfinder\app\main\controller\controller.php:74
[22-Jun-2018 13:33:33 UTC] PHP  13. DB\SQL\Session->__construct() G:\webpages\pathfinder\app\main\controller\controller.php:141
[22-Jun-2018 13:33:33 UTC] PHP  14. session_set_save_handler() G:\webpages\pathfinder\app\lib\db\sql\session.php:202
[22-Jun-2018 13:33:33 UTC] PDOStatement: Duplicate entry '271683000370650e53eaebb466051ba7' for key 'PRIMARY'
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/base.php:2219] Base->error()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/sql.php:235] user_error()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/sql/mapper.php:439] DB\SQL->exec()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/cursor.php:245] DB\SQL\Mapper->insert()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/db/sql/session.php:95] DB\Cursor->save()
[22-Jun-2018 13:33:33 UTC] [G:/webpages/pathfinder/app/lib/base.php:2091] session_commit()
```

**Comment by exodus4d** [comment] 2018-07-27 19:39
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*

**Closed by exodus4d** 2018-07-27 19:39 UTC
Labels: minor bug
