### ISSUE TITLE
Issue >> Release 1.4.1 >> Type select not presented on new entry until page reload

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#695] opened 2018-09-30 12:41 UTC
When pasting new signatures into the mapper there is no option to select the type of the wormhole until a reload of the page is completed. 

Issue occurs on any entry being added (WH/Data/Relic/Gas)

Version 1.4.1

**Comment by mrurb** [comment] 2018-09-30 14:02
Duplicate of #690

**Closed** 2018-10-05 23:51 UTC
Labels: duplicate
