### ISSUE TITLE
Cannot put Owner in Intel Tab

### ISSUE THREAD

**Issue by Meganitrospeed** [exodus4d/pathfinder#842] opened 2019-08-15 17:12 UTC
https://i.imgur.com/Jf05Fus.png

Just write anything into the tab and you get that error message

**Comment by CalMatar** [comment] 2019-08-15 23:10
I have found the same issue. I thought it was similar to an issue I had previously where the corporation was not showing up but when I looked in game it did not show up in the search there either but as you can see by the second screen shot that is not the case here (that previous issue was resolved by CCP "somehow") so I am not sure where the issue is if it is something on their side or your side. Since this just started today after a patch I am going to presume it is on the side of CCP but will await your further advice. 
@Meganitrospeed I will give you some advice to help out anyone having this issue to keep your intel flowing, put the corp names in the NOTES section (I usually put the Alliance name there anyway) which is what I was doing when it was running slow. At least you will have the info in there.

![Screenshot_82](https://user-images.githubusercontent.com/42744905/63132576-8ee34b80-bf8f-11e9-998c-59e6039543b7.png)
![Search Failed](https://user-images.githubusercontent.com/42744905/63132577-8ee34b80-bf8f-11e9-9fb2-d2900eba8326.png)

**Comment by Meganitrospeed** [comment] 2019-08-15 23:38
@CalMatar Good to hear that other people is having the same issue, we where already putting almost everything in Notes ( Screenshots and general Intel ) but newbro`s keep insisting in using Intel, so i opened the issue in case exodus wasnt aware of it
BTW: Is Multichar tracking working for you?

**Comment by CalMatar** [comment] 2019-08-17 00:33
@Meganitrospeed what do you mean by Multichar tracking?

**Comment by Meganitrospeed** [comment] 2019-08-17 00:46
@CalMatar Tracking 1 Caracter Per tab, ( Tracking your alts in Pathfinder ) Its currently not working for me but still want to know if more people are having this issue

**Comment by CalMatar** [comment] 2019-08-17 02:13
@Meganitrospeed do you mean on different maps or on the same map? I have tried both on the same map and that works fine. I am currently only using three maps that do not "intersect" and my two toons are in the same wormhole so if you mean on different maps then I would have to try something else to try that but have never had a problem before. I know this is probably a dumb question but they are all logged in right?

**Comment by CalMatar** [comment] 2019-08-22 20:04
@Meganitrospeed this is working now.

**Comment by exodus4d** [comment] 2019-10-05 12:39
@Meganitrospeed The bad response error from your screen is related to an invalid ESI response. Probably a temporary problem with CCPs API.

**Closed by exodus4d** 2019-10-05 12:39 UTC
