### ISSUE TITLE
[Bug] Pod kills/death clone causes direct connection to system death was registered in

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#259] opened 2016-07-23 16:51 UTC
Issue: 
When a pilot is podded (either friendly, hostile or death cloning) pathfinder is registering the jump as a wormhole jump and making a direct connection to where the medical clone is registered.

**Comment by garemoko** [comment] 2016-07-25 08:53
Duplicate of https://github.com/exodus4d/pathfinder/issues/235

**Closed** 2016-07-25 08:53 UTC
Labels: duplicate
