### ISSUE TITLE
Account Settings wont save

### ISSUE THREAD

**Issue by doctorofdipping** [exodus4d/pathfinder#911] opened 2020-01-28 20:48 UTC
When I go to menu -> account settings -> Sharing. I enable private map sharing, hit save. I get a pop-up saying account saved, but if I go back to my account settings nothing has changed and I still can't share my map. Tried different browsers, different computers, and even mobile. Still not saving

**Comment by doctorofdipping** [comment] 2020-01-28 20:51
*both my characters are having this issue, and neither can share with the other

**Comment by porowns** [comment] 2020-01-29 14:53
I've had this issue.

**Comment by zap2zero** [comment] 2020-01-29 15:18
Same here on my server, the options simply don't work.

**Comment by CalMatar** [comment] 2020-01-30 04:16
@exodus4d This issue is happening across all versions of the maps and both private and public server. I hope this can get fixed soon as this is a MAJOR problem with a lot of us that share maps between different corporations outside of our alliances.

**Comment by CalMatar** [comment] 2020-02-06 16:29
I think there is another issue with this bug that is affecting the Management section as well. I have two of the three required roles for the management of Pathfinder but the system will not let me log in as a manager as it tells me that I do not have the required roles. I have verified that I have the Roles, not the Granted Roles for security_officer as well as for personnel_manager although in the game they are Security Manager and Personnel Manager. I had the management tag and ability up until this bug started so whatever is causing this is probably also causing the other issue as well. I can not make any modifications to my maps now until this is remedied.

**Comment by Caffe1neAdd1ct** [comment] 2020-02-16 22:43
Duplicate of https://github.com/exodus4d/pathfinder/issues/911 ?

**Comment by CalMatar** [comment] 2020-02-16 23:02
Appears to be, except for my last comment about the Management Flag.

**Comment by Caffe1neAdd1ct** [comment] 2020-03-06 22:43
Fixed in a pull request, if you're able to test feel free: https://github.com/exodus4d/pathfinder/pull/922

**Comment by exodus4d** [comment] 2020-03-09 22:00
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #889
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*

**Closed by exodus4d** 2020-03-09 22:00 UTC
