### ISSUE TITLE
Scrolling in Menus

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#696] opened 2018-10-01 15:20 UTC
I do not know if this is a bug or a wish list item but I can not use my mouse wheel to scroll through any of the menu items, such as the structure menu when adding structure information to the Intel section, and in fact it actually scrolls the main page even though I am hovered over the menu. 
If this is actually in another post somewhere I could not find it so here it is. If you need screenshots or something I might be able to help.

**Comment by CalMatar** [comment] 2018-10-01 15:39
I have NEVER been able to scroll in ANY of the menus not just the wormhole list and not just in the last revision. It is in ALL of the menus and has been since I have been using Pathfinder (which to be honest has only been about 4 months or so) and I am talking about using the mousewheel to scroll not clicking on the scroll bar and manually scrolling just to be clear.

**Comment by exodus4d** [comment] 2018-10-05 23:50
@CalMatar This is a screen record from the upcoming `v1.4.2` and the fixed #692 . Could this fix your problem, too?
![acroll](https://user-images.githubusercontent.com/9299033/46564842-2147a700-c90a-11e8-84c0-65a7500341d4.gif)

**Comment by CalMatar** [comment] 2018-10-08 15:40
It looks like it. We shall see when it comes out.

**Comment by CalMatar** [comment] 2018-10-10 02:00
I still can not scroll in the menus as above is showing. I have tried clearing my cache and it did not help. I will be restarting my computer in the morning and will try it again tomorrow with clearing cache and history again.

**Comment by CalMatar** [comment] 2018-10-10 18:45
I have restarted my computer and have cleared cache and cookies twice and I am not the only one who can not scroll in the menus still.

**Comment by Tupsi** [comment] 2018-10-11 10:30
I can confirm that it isnt working on my end neither with 1.4.2 installed.

**Comment by exodus4d** [comment] 2018-10-11 10:31
Could you please, give me some more information about the Browser + Version ?

**Comment by eboaen** [comment] 2018-10-11 12:38
Still an issue for us as well.  Chrome, 69.0.3497.100

**Comment by CalMatar** [comment] 2018-10-20 16:07
I am using Firefox 62.0.3 (64-bit)

**Comment by exodus4d** [comment] 2018-11-29 08:56
Should be fixed in the next release.

The problem was, the the required "mousewheel" JS library got loaded in the wrong order. That´s why it worked in my "develop" environment but not with the "build" JS files... sry

**Closed** 2018-12-02 12:12 UTC
Labels: minor bug
