### ISSUE TITLE
Feature Request: Bookmark Name Generation

### ISSUE THREAD

**Issue by Kimeni** [exodus4d/pathfinder#361] opened 2016-10-23 00:05 UTC
A non critical, but nice quality of life feature my corporation is missing after the migration -

After scanning down and pasting the signatures of a system, being able to copy a generated bookmark name by mousing over, or otherwise having it somewhere available to 'ctrl-c' Which could include something like "<WH Alias> <Site Category> <Sig ID> <Site Name>"

So, just for example, something like "WH4 xR BCY Ruined Serpentis  Temple"

Where the 'xR' indicates it is a relic site.

Or "WH6 xD XID Sparkling Transmitter", where xD is a Data Site.

Again, simply removing human error, and allowing for a standard appearance and system of bookmarking. Also saving time, having to type the things out. Just being able to copy and paste your bookmark's name into the field is a nice feeling.

**Comment by dnolen** [comment] 2016-10-23 18:51
If possible could you consider setting up some form of automated naming convention field with an iterating number/letter increment. 

When a new system is populated; example a high sec have it marked as HSa/1 (naming convention could be customization based on corp preference)

**Comment by atkinsj** [comment] 2016-10-25 18:44
The problem with this idea is that everyone has a different bookmark name
scheme. It would need to be configurable on a per map basis which could be
a pita.

**Comment by exodus4d** [comment] 2016-10-26 16:54
Thanks for your feedback. As @atkinsj  said, the problem is that everyone has a different bookmark naming convention. Making it configurable is to much work. At this point I´m not planning to implement something like this.

**Closed by exodus4d** 2016-10-26 16:54 UTC
