### ISSUE TITLE
Connection points spawning on their own

### ISSUE THREAD

**Issue by vivace-io** [exodus4d/pathfinder#269] opened 2016-07-27 23:00 UTC
So I'm watching my map spawn a bunch of connections on its own. Refreshing the web page removes these connections (they are not saved), but they start spawning again. Some of my alliance members are reporting that their browser tab crashes after long periods of time, and I'm wondering if this might be it.

[Here's a picture after a few minutes of it running like this.](http://i.imgur.com/Gv5j8MZ.png)

I tried fiddling around with the settings over [here](https://github.com/exodus4d/pathfinder/blob/master/js/app/map/map.js#L108), but I had no luck. I'm still trying to trace the drawing calls back, but I have had no luck so far, sadly.

**Comment by exodus4d** [comment] 2016-07-29 19:39
### :grey_question: Bug details required
Thanks for your bug report. Unfortunately I couldn't verify/reproduce this. :disappointed:
Could you please provide us with some detailed information about this issue...

- **Version:** Which version of *Pathfinder* is being used? (e.g. `v1.1.2`)
- **Server:** Which server/installation is being used? (e.g. "*private*" or "*public*")
- **Browser:** On which browser have you determined this issue? (e.g. "*Chrome v52*")
- **Frequency:** How often have you seen this bug? (e.g. "This happens **any time** a user clicks on a System.")
- **Reproducible:** If you found a way to reproduce this, please tell us how.

#### If this bug is on a "*private*" server/installation, please add additional environment information that could be helpful:

- **Web-Server:** (e.g. "*Nginx*", "*Apache*")
- **PHP:** (e.g. `v7.0.8`)
- **Database:**` (e.g "*MySql v5.6*")

***
*Auto-generated response*

**Comment by vivace-io** [comment] 2016-07-30 03:35
Requested information:
- PF Version: v1.1.1
- Server: Public to my corp
- Browser(s): Latest at this time of writing, Chrome(51.0.2704.103) and Firefox (47.0.1)
- Frequency: Consistent on every page load.
- Reproduction: Unknown as to the initial cause, but error is consistent across for all my members (no one has reported an exception).
- Web Server NGINX
- PHP v7.0.8
- MySQL v14.14 dist 5.7.13 (64 bit)

My biggest problem is that we are unable to switch over entirely to Pathfinder as it is causing my member's browsers to crash frequently.

A mail has been sent to you in game with a link to the server. Feel free to see if the bug persists for you.

**Comment by exodus4d** [comment] 2016-07-30 21:25
Thanks a lot! I found a bug, that **could**  be responsible for that issue.
I´ll scan the code for potential problems...

In the meantime you could upgrade to `1.1.2` and check again. This includes some major JavaScript library updates (e.g. jQuery 1.11.3 -> 3.0.0,...). This could help as well.

**Comment by vivace-io** [comment] 2016-07-30 22:37
Awesome, glad we weren't just hallucinating! I'll upgrade later tonight and report back in a few hours.

**Comment by vivace-io** [comment] 2016-07-30 22:54
Real quick - upgrade instructions specify that import SDE in to the new tables can be done from `/setup` - I don't see the option. Any clues? If it accidentally was not included, what tables from the SDE needs to be imported?

**Comment by vivace-io** [comment] 2016-07-30 23:02
I have updated tag v1.1.2 and the problem persists. If you need me to add you back in to the map, let me know either here or in game and I'll add you back in.

**Comment by exodus4d** [comment] 2016-08-28 10:01
I´m, pretty sure I found your problem. I could reproduce this behavior by changing some `active` column flags in table `system`. But this should not happen to *normal* users. 

**It looks like your "*foreign key constraints*" are not properly setup.**

System connections should automatically be dropped by *PF* when a systems gets deleted. It looks like you have connections in your DB to systems that no longer exists! Please check your *constraints* for all tables (especially table `connection`). They should look like this:

![foreign_keys](https://cloud.githubusercontent.com/assets/9299033/18032910/9d0cdb2e-6d15-11e6-889c-ee128a78633b.png)

***

#### I made some *client side* (*Javascript*) improvements, to prevent auto-spawning for broken connections. But the problem itself needs to be fixed in your DB Schema:

- The existence of `source` **and** `target` systems are now checked before a new connections is established.
- A *Javascript* warning was added when a systems does not exists (which should never happen if your DB is consistent)! 

![connection_warn](https://cloud.githubusercontent.com/assets/9299033/18032940/de2e594c-6d16-11e6-8bec-0ba763e922be.png)

**Comment by exodus4d** [comment] 2016-09-03 20:35
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*

**Closed by exodus4d** 2016-09-03 20:35 UTC
Labels: minor bug

**Comment by vivace-io** [comment] 2016-09-04 00:38
Thanks for your hard work. I'll check this out tomorrow.

Cheers.

**Comment by vivace-io** [comment] 2016-09-04 01:20
Went ahead anyways - 

Just did a full re-install and having issues even creating a map. Unrelated to this issue. Sent you an e-mail requesting a slack invite and we can chat there.
