### ISSUE TITLE
CCO Admin Login problem

### ISSUE THREAD

**Issue by tezdal** [exodus4d/pathfinder#643] opened 2018-06-22 12:12 UTC
Hi. i have a problem with auth in CCO admin

Error 500
Status 'session_set_save_handler(): Cannot change save handler when session is active'
Message: Internal Server Error

```
root@eve:/usr/ports # php -m
[PHP Modules]
Core
ctype
curl
date
filter
gd
hash
iconv
json
libxml
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
Reflection
session
SPL
standard
zlib
zmq

```

`root@eve:/usr/ports # php -v
PHP 7.2.6 (cli) (built: May 31 2018 01:15:56) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
`

```open() "/var/www/pathfinder/public/js/v1.3.5/app/.js" failed (2: No such file or directory)```

**Comment by exodus4d** [comment] 2018-06-22 18:09
Hi, Thanks for reporting. This is a duplicate of #595

Please read this issue, and check if my last commit fixed the issue for you:  38ceb92

**Closed** 2018-06-22 18:09 UTC
Labels: duplicate, minor bug
