### ISSUE TITLE
[Feature Request/Bug] Updating Signature Description

### ISSUE THREAD

**Issue by krjohnn** [exodus4d/pathfinder#253] opened 2016-07-19 18:20 UTC
Hi!

I've written about this before, but I see that is was not implemented or perhaps it's broken again?
Here's the problem.

Signatures in EVE have 3 stages when scanning.
Stage 1 - Unknown Cosmic Signature Group, Unknown Name ( We know nothing about it )
Stage 2 - Known Cosmic Signature Group, Unknown Name ( We know it's a Data site )
Stage 3 - Known Cosmic Signature Group, Known Name ( We know it's a Data site and Central Serpentis Survey Site )

The problem is that when you paste a signature that is scanned in Stage 1 or Stage 2, it shows up and updates properly in the signature list, however, when you have scanned it down to Stage 3, and then paste it again to update it - it does not update the Description field in the signature list - it remains as Stage 2 signature in the signature list, without the Known Name information.

The only workaround for this is to remove the signature from the signature list and paste it again, then it DOES update the Description field with the Known Name.

Name and Group are the EVE in-game fields in Probe Scanner (English client)

**Comment by krjohnn** [comment] 2016-08-13 21:33
Any clues about this one ? :D

**Comment by dkrotil** [comment] 2016-08-14 00:02
Will ask corpmates , which are responsible for scanning if they experience same behavior .

**Comment by krjohnn** [comment] 2016-08-14 02:33
Basically it goes like this 

Stage 1 - paste it in Signature Reader - Updated correctly
ZBF-320	Cosmic Signature			1.9%	8.24 AU

Stage 2  - paste it in Signature Reader - Updated correctly
ZBF-320	Cosmic Signature	Data Site		28.9%	7.62 AU

Stage 3  - paste it in Signature Reader - No Updates to the signature at all
ZBF-320	Cosmic Signature	Data Site	Limited Sleeper Cache	95.7%	7.58 AU

So if you paste the Signature in each of its Stages, it will not update when pasting Stage 3 information, however, it will update the Description field if you remove the Signature and paste Stage 3 again.

**Comment by dkrotil** [comment] 2016-08-14 14:34
OK, I asked my probers and they saying, that they don´t use stage 2 .

**Comment by krjohnn** [comment] 2016-08-14 14:40
Yeah but it doesn't matter if the signature has been added in Stage 1 or Stage 2, it will not update the Description when updating Stage 3 information.

You have to remove the signature then re-add it.

I think it would make sense that it updated when you paste Stage 3 information to the Signature Reader just like it updates signature from Stage 1 to Stage 2

**Comment by exodus4d** [comment] 2016-08-14 15:06
**This is not really a bug, It´s more "feature". Let me explain this:**

1. signature parsing (sig reader, copy&past) requires some kind of string "mapping". (E.g. get a valid **ID** for signature name "Limited Sleeper Cache" and store it into DB).
2.  If the signature is **known** by *Pathfinder*, the "**type**" select will hold this information. This **just** works in wormhole systems (wormhole signatures like data, relic, gas, ... )! There are to many signatures in *EVE*..... I cant maintain a full list for all regions.
3. If a signature name is **unknown**, the signature name will be saved as **description** (raw text). This is why **type** selects are **not** available on HS/LS/0.0 systems. (see 2.)

The signature name "Limited Sleeper Cache" seems to be a **HS** signature: [source](http://de.sistersprobe.wikia.com/wiki/Limited_Sleeper_Cache) and is not available in WH systems. Therefore the signature name gets saved as **description**.

I explicit `unset()` the description from been overwritten [signature.php#L150](https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/api/signature.php#L150)
Let us assume someone changed the description manually in the meantime, e.g. added more information to it. This would be overwritten by an update (stage 3).

But I´ll try to **allow** descriptions to be "overwritten" (saved) if there is not already a description saved.

**Comment by exodus4d** [comment] 2016-08-14 15:22
@krjohnn Thanks for your last https://github.com/exodus4d/pathfinder/issues/253#issuecomment-239652467 ! With the signature name, I could reproduce/understand this issue. Should be fixed with the upcoming release.

**Closed** 2016-08-15 19:09 UTC
Labels: minor bug
