### ISSUE TITLE
Pathfinder database does not fully populate and leads to errors

### ISSUE THREAD

**Issue by Ulaxidor** [exodus4d/pathfinder#158] opened 2016-05-17 02:43 UTC
I’ve installed pathfinder using version 1.10.0 of the standard nginx without using the p5hb ( h5bp/server-configs-nginx ) repository because it simply does not work, as in it will not host any host file and will not listen on any port in my hosts file.  The standard nginx is able to host pathfinder but my Pathfinder database is incomplete https://gyazo.com/d558566a28020d105cace7bf4cc1d103.  It results in this https://gyazo.com/4a16bffc1f7cf47a5c7e693c90c820cc.  A pop up error “Route not found” occurs when any kspace connection is clicked ( https://gyazo.com/59141af6bd6778fbe3bf5ddb8b3b0f37 ).  It also will not load the system kills from zkill as it constantly loads as seen in the GIF.  Here is error from the developer tools view ( https://gyazo.com/975b331f6d4a2c481d12f89b9be62a9f ).  
Here is what my https://domain/setup looks like  https://gyazo.com/e9120caf5b017957c8acf374181c261a  and https://gyazo.com/243b11ff3f86454a4cc8ef402e10df4a.
In addition I get this perpetually loading page ( https://gyazo.com/79fc917cae72434ebeb3a46c6f59d09e ) each time I click on "Setup tables."  This is the error in the developer tools view ( https://gyazo.com/21be08990c307dea1ba1a00ab2e0b5f2 ).

--Update--
After removing the database and repopulating it and installing a few java apps including oracles jdk 8.0, and Jquery, and requirejs, I am still getting the same errors ( https://gyazo.com/a53c9e1e6d19f933a73f3f29a197d883 ) cant path from kspace connections despite importing the pathfinder.sql database.

Am I getting these issues because I am not using the p5hb nginx repository?  Any help would be greatly appreciated!

**Comment by Tupsi** [comment] 2016-05-17 05:33
check the installation. There is a .sql file you need to manually import. This is missing in the wiki documentation.

**Comment by Ulaxidor** [comment] 2016-05-17 06:01
Thanks for your reply Tupsi!  I have tried to import that pathfinder.sql into my pathfinder database several times, however that only allows me to see the wormhole information regarding their static connections.  However I am still getting 4  "Route not found" errors every time i click on a kspace, and every time i use the "route search" module.  In addition the killboard portion still does not load, and appears to be a permissions issue ( https://gyazo.com/947666fa49d47f3af3abaf082c8bc3ed )

**Comment by Tupsi** [comment] 2016-05-17 07:39
which pathfinder are we talking here? Are you using the master or develop branch?

**Comment by Ulaxidor** [comment] 2016-05-17 07:50
Its the master branch ( https://github.com/exodus4d/pathfinder.git )

**Comment by exodus4d** [comment] 2016-05-17 08:07
@Ulaxidor 
- Please clear your `/cache` dir afterwards. Routes that could not be found, were cached. This is a bug and is already fixed in in `develop` branch.
- The zKillboard is also broken in the `develop` branch. This is because zKillbaord changed their CORS Headers (this is fixed in develop branch too).
- If you want to check out the current develop branch. There is a fresh testing environment running it: https://www.dev.pathfinder-w.space/

**Comment by Ulaxidor** [comment] 2016-05-17 08:10
@exodus4d 
Thank you!  That worked!

**Comment by Ulaxidor** [comment] 2016-05-17 08:23
@exodus4d 
The kspace system statistics is the only portion that is not loading properly now other than the zkillboard portion that is.  Instead of indicating the Jumps over a 24 hour period, Ship/POD kills and NPC Kills, there is simply a blank space (https://gyazo.com/77f04b410cb4e35b6b2c5c57f1433dca).  Is there a fix for this or is this also related to the zkillboard issue?

**Comment by exodus4d** [comment] 2016-05-17 08:50
@Ulaxidor This is not a bug, You don´t have any jump data in your database ;) This jump/kill data should be imported by a cronjob. Check the Wiki for more information. 
If you have problems with setting up a cronjob (`$ crontab -e` ...) for this. I´ll try to help you. It should be done in 1min, it´s just a "one-liner".

**Comment by Ulaxidor** [comment] 2016-05-17 09:29
@exodus4d 
I would definitely appreciate your help with that!  As per the wiki I have created the cron.phpx file, then placed it in my root installation directory.

**cron.phpx contents, modified only the first line, the other 4 echo lines are exactly as they are in the wiki:**
exec('wget -qO- /dev/null /opt/pathfinder/pathfinder/app/cron &> /dev/null', $out, $result);

then I’ve made cron.phpx executable by using the chmod 755 command on it.

**crontab -e:**
* * * * * php /opt/pathfinder/pathfinder/cron.phpx

How does that look?  In the first line of the cron.phpx file, should I add .ini to the word cron to specifically reference the cron.ini file or is “cron” sufficient?

**Comment by exodus4d** [comment] 2016-05-17 11:36
Yeah will copy my `crontab -e` line when I´m back home. But you don´t need the *.phpx file . This is just a "workaround" for those who have to specify a script that triggers the script. 
You realy just need a single line in `crontab -e`  ithat triggers the job.

**Comment by exodus4d** [comment] 2016-05-17 17:44
@Ulaxidor Just add the following line to `$ crontab -e` file (don´r forget to replace the project path!)

```
* * * * * cd /var/www/pathfinder.com/public_html; php index.php /cron >> /var/log/cron-www/pathfinder.log 2>&1
```

If *crontab* is not already installed, check this for more information: https://www.digitalocean.com/community/tutorials/how-to-use-cron-to-automate-tasks-on-a-vps

> **Hint:** The log file path at the end is *optional*. This will log any output (e.g. errors) to a *.log file.

**Comment by exodus4d** [comment] 2016-05-17 18:43
This information is now added to the wiki:

https://github.com/exodus4d/pathfinder/wiki/Cronjob

I have reworked the page, added some more information....

**Closed by exodus4d** 2016-05-17 18:43 UTC

**Comment by Ulaxidor** [comment] 2016-05-17 18:57
@exodus4d 
Thanks!.  I had to tweek that command just a little to get it to output to the log file.
* * * * * php /opt/pathfinder/pathfinder/index.php /cron >> /opt/pathfinder/pathfinder/logs/pathfinder2.log 2>&1

However that log file now contains multiple copies of this line: 
Class 'Controller\Controller' not found

The manual command "curl mydomain.com/cron" returns this:
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>

The map will still not load the Jumps, Ship/POD Kills, NPC Kills section.

**Comment by exodus4d** [comment] 2016-05-18 16:55
I have fixed a small issue on the develop branch, which belongs to this issue: 95ff8cd93f709fc53510a0ebd85e369ea6994576
