### ISSUE TITLE
Cannot track Character, Slow Connection Issues

### ISSUE THREAD

**Issue by GZPerdi** [exodus4d/pathfinder#755] opened 2019-02-21 06:54 UTC
Ever since the recent shutdown issue Pathfinder has been unable to track my characters, my corpmates seem to have no issue, but I always have a 'slow connection' to pathfinder and it won't update where I am on the map or regions I explore, it shows my character being online, but no map info. Any possible fix?

**Comment by jajmo** [comment] 2019-02-21 13:49
Duplicate of #754.

**Closed** 2019-05-11 11:49 UTC
Labels: duplicate
