### ISSUE TITLE
Rally point - poke doesn´t send email anymore

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#438] opened 2017-02-10 08:02 UTC
Because I had working Slack integration, I´m confident, that in version 1.1.6 was working everything as expected, after upgrade to version 1.2, we don´t getting emails anymore. Even I set debug to 3 I don´t see anywhere in php / nginx logs errors.

**Comment by MorpheusXAUT** [comment] 2017-02-16 21:40
Just making double-sure you didn't overwrite this setting while upgrading to v1.2.0: you did set up the `RALLY_SET` setting in the `PATHFINDER.NOTIFICATION` section of the `app/pathfinder.ini` config file, right? 😄 

There's not much else to change in this file, so it could be overlooked pretty easily (at least I did during the last upgrade >.>)

**Comment by dkrotil** [comment] 2017-02-16 22:37
Nope, RALLY_SET has working email address set, have double check that.

**Comment by MorpheusXAUT** [comment] 2017-02-16 22:43
Started poking around myself a bit, looks like the `From:` header is malformed when it is sent to the SMTP server.

I've captured some logs and the value is changed from `Pathfinder <pathfinder@morpheusxaut.net>` to `<Pathfinder>, <pathfinder@morpheusxaut.net>` somewhere while being passed around by pathfinder and the library. Currently still trying to figure out where exactly that is.

**Comment by MorpheusXAUT** [comment] 2017-02-17 01:18
Looks like this was caused by the Fat Free Framework upgrade from 3.5.1 -> 3.6.0, committed in 03c1d53fd613e3750045510746ad6d0980b8e137. To be more precise, F3 [changed their email-parsing regex](https://github.com/exodus4d/pathfinder/commit/03c1d53fd613e3750045510746ad6d0980b8e137#diff-a1527b44be2d898f9a421d7c584ea28dR252) which leads to it parsing the value provided by pathfinder incorrectly.

Pathfinder sets the `From:` address as `Pathfinder <from@example.com>`. Since F3 changed to detecting the From-"Name" in double-quotes (using the regex `(?:".+?" )?(?:<.+?>|[^ ,]+)`), it will recognise the `Pathfinder` part as a separate address, thus incorrectly adding a second set of chevrons.

This leads to further issues since the SMTP servers receives a `MAIL FROM:` values of `<Pathfinder>, <from@example.com>` instead of the expected `<from@example.com>`. Since that is obviously an incorrect value, the SMTP servers reject the mail and notifications thus don't get sent out.

The simple fix? Adding two double-quotes around the `Pathfinder` string. Sounds stupid, but works, confirmed it with my instance 😄 

I'll be sending a PR shortly @exodus4d

**Comment by exodus4d** [comment] 2017-02-17 20:30
I added a new "SMTP" page to the [wiki](https://github.com/exodus4d/pathfinder/wiki/SMTP)

**Closed** 2017-03-11 19:53 UTC
Labels: minor bug
