### ISSUE TITLE
Issues with SSO

### ISSUE THREAD

**Issue by ecortinas** [exodus4d/pathfinder#431] opened 2017-02-01 01:28 UTC
So I have deployed pathfinder successfully. The issues I am having is that when I click on the SSO link it directs to domain.com/sso/requestAuthorization instead of domain.com/subfolder/sso/requestAuthorization

How to fix?

**Comment by MorpheusXAUT** [comment] 2017-02-01 14:00
Did you change the config as required? You have to change the BASE config value (in environment.ini) as mentioned in the [wiki for configuration](https://github.com/exodus4d/pathfinder/wiki/Configuration).
Assuming your domain is "example.com" and you want to run pathfinder at "http://example.com/pathfinder", you'd have to set the value of _BASE_ to "/pathfinder" and the value of _URL_ to "example.com" (without the "") in your environment.ini file.

Furthermore, you probably have to change the application you created at [CCP's third party dev portal](https://developers.eveonline.com/applications) and modify the callback URL example provided in the [wiki](https://github.com/exodus4d/pathfinder/wiki/CREST) to include your path as well.
Using the same example as above, you'd set the callback URL to "https://example.com/pathfinder/sso/callbackAuthorization". Saving the updated app should apply changes immediately and redirect you appropriately.

**Comment by abeazam** [comment] 2017-02-01 14:37
I am having the same issue

environment and pathfinder ini files are both updated as per your wiki

Due to my not being a web dev I could have missed something. I am how ever a Developer so considering the instructions I should be able to get it working

Things it could be:
using a shared host: 
    no sockets
    no control of DB version(DB seems to be running fine) (I get a chk in setup)
    No  NodeJS(not seen this on your requirement list but have seen files reference it)
domain is sub so "pf.mydomain.com/Pathfinder"
    /setup is still there does that need to be blocked before it works?

**Comment by MorpheusXAUT** [comment] 2017-02-01 15:13
Just tried replicating it with my dev instance and you're indeed correct. It appears like pathfinder doesn't always prepend the base path properly.

@abeazam The things you've mentioned should be no problem, at least as far as I can see (although I'm no PHP dev either 😄 ). I have set up a fresh install as well and it's not working on their either - using a dedicated VPS with the listed requirements installed.

**Comment by abeazam** [comment] 2017-02-01 16:23
well I have moved it to the root and it is mostly working now. Thx :)

**Comment by abeazam** [comment] 2017-02-02 10:19
@ecortinas  I did a bit more digging and I think I have found the reason it was breaking when you used a sub folder.

The link for the redirects is not based on the URL/Path set in the environment.ini

It looks like its based on the path set in the routes.ini that is where you set the sso path

**Comment by exodus4d** [comment] 2017-02-02 18:19
Thanks for the report. Ill check if there is anything wrong with the `BASE` path, especially on sub-folder installations. 

What I can confirm is, that non-sub-folder installations have no problems

**Comment by Grandnovus** [comment] 2017-04-24 19:05
I'm in the same position. Installed to sub directory example.com/pathfinder

Set environment.ini correctly, can access the webpage - But SSO, and setup return 404's. 

Tried editing routes.ini, but changing 

GET @setup:         /setup                      [sync]  =   Controller\Setup->init
to
GET @setup:         /pathfinder/setup           [sync]  =   Controller\Setup->init
Removes the setup option from the webpage. Tried different spacing's as well with no luck

SSO returns a 404 as well upon clicking the login button, at http://example.com/sso/requestAuthorization - SSO application callback is set to http://example.com/pathfinder/sso/callbackAuthorization

Aaaand i'm running out of ideas. (Example.com is a replacement for the actual web address) - Sent an email asking for access to the pathfinder slack, but haven't heard back yet.

**Comment by exodus4d** [comment] 2017-04-30 12:10
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*

**Closed** 2017-05-01 18:18 UTC
Labels: minor bug
