### ISSUE TITLE
Pasting WH signatures into the signature reader should automatically create a new connection on the map

### ISSUE THREAD

**Issue by moe-alabel** [exodus4d/pathfinder#549] opened 2017-11-20 14:04 UTC
This behaviour should mimic tripwire. If I scan down all of my signatures and 3 out of the 5 lets say are wormholes. When I paste them into the sig reader, they should create new unknown connections on the map. Kind of like how tripwire works

**Comment by SeriousM** [comment] 2019-09-05 09:29
This is a duplicate of #798

**Comment by exodus4d** [comment] 2019-10-30 22:53
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*

**Closed by exodus4d** 2019-10-30 22:53 UTC
Labels: feature request
