### ISSUE TITLE
enable map invite is not being saved.

### ISSUE THREAD

**Issue by dekeonus** [exodus4d/pathfinder#920] opened 2020-03-05 22:49 UTC
under account settings - share setting the dis/enable map invite button does not update the database when the state is toggled.
This is evident on www.pathfinder-w.space
On a local installation I was able to force enable the option by directly editing the database. However once enabled, the state can't be disabled without directly editing the database again.

**Comment by CalMatar** [comment] 2020-03-07 03:16
This is a duplicate of two tickets. One is 911 and the other is 889.

**Comment by exodus4d** [comment] 2020-03-10 18:50
Yeah this is already fixed in #911 (will be released in ~2 weeks)

### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*

**Closed by exodus4d** 2020-03-10 18:50 UTC
