### ISSUE TITLE
Route finder occasionally shows 'not found' despite k-space exits being present

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#244] opened 2016-07-14 01:39 UTC
I haven't been able to find a way to reliably reproduce this yet but it happens fairly frequently. I have a number of k-space exits (lowsec, highsec) present on the map and it is showing 'no route' to some systems. The four major route hubs work -- but if I search for a fifth system it doesn't work.

**Comment by exodus4d** [comment] 2016-07-15 20:24
Could you please give me the two systems (source/target) when this happens the next time? Thanks

**Comment by atkinsj** [comment] 2016-07-15 20:27
I'm seeing this now on Old Man Star to 2O9G-D.

**Comment by exodus4d** [comment] 2016-07-31 16:41
#### Search depth of the route search algorithm can now be configures.

It took me some time to figure out what exactly the problem was :unamused: . Finally I figured out it was problem, caused by "security feature" I implemented a while ago.....

The recursive search depth was limited to **5000** iterations. For some complex maps, combined with long distance searches (e.g. "*Cobalt Edge*" to "*Amarr*") this is by far not enough... The problem with increasing this, are performance problems (RAM limit) on small VPS/SharedServers.

What I have done:
- Added `SEARCH_DEPTH` to `pathfinder.ini` and make it adjustable 
- Changed default depth from **5000** to **7000** (this works well for me on testing)

I´ll keep watching this. If this change causes other problems, we should decrease the default.

***

#### Technical note:
I added new return values `depthSearched` and `maxDepth` to the *Ajax* search request (`/api/route/search`). This information is not visible on the webpage but it is nice to check on the dev-tools how close a search was to the iteration limit:

E.g. "*E0DR-G*" -> "*Amarr*" (took **4583** iterations)

![test](https://cloud.githubusercontent.com/assets/9299033/17277893/6edc6b3e-574e-11e6-90e8-3f16a59925de.png)

**Comment by atkinsj** [comment] 2016-07-31 16:47
Thanks exodus! I hadn't had a chance to look at this but it sounds like a tough one so I'm glad it was you and not me! :)

I'll have a tihnk about this more though because there has to be a more effective way to calculate these routes; compared to something like dotlan or Garpa Topological Survey it seems very slow and intensive. Understand this is a very difficult problem though.

**Comment by exodus4d** [comment] 2016-08-01 18:27
Thanks,

This should be a E_NOTICE on PHP7 (They have changed the level)
Documentation: [Migrating from PHP 5.6.x to PHP 7.0.x](http://php.net/manual/de/migration70.incompatible.php) (scroll down)

The default on PHP7 is `error_reporting = E_ALL & ~E_NOTICE`, Therefore I haven´t seen this :(
Documentation [Runtime Configuration](http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting)

Should be fixed now.

**Closed** 2016-08-15 19:09 UTC
Labels: minor bug
