### ISSUE TITLE
Signature issues (v1.4.1)

### ISSUE THREAD

**Issue by cwalker94** [exodus4d/pathfinder#690] opened 2018-09-26 19:24 UTC
I have the latest v1.4.1 installed and a user has reported an issue that they weren't having with 1.4.0 when pasting probe scan results. This is what they had to say (I'm unable to test it myself, as I don't have access to EVE at the moment).. 

- You have to reselect a system to choose the WH and connection type
- It doesn't show all anomaly types like it used to

Possible steps to reproduce 2nd issue??

- Pasted results, and chose a site for the relic by hand
- Pasted again after that and the relic lost it's type, even with it being scanned down

**Comment by Slivo-fr** [comment] 2018-09-27 09:28
I have users reporting the same issues

**Comment by Slivo-fr** [comment] 2018-09-27 11:31
What about the wormhole type part ?

**Comment by exodus4d** [comment] 2018-09-27 11:42
Looks also good on my side:
![signature_bug_reproduce_attempt2](https://user-images.githubusercontent.com/9299033/46143721-272eef80-c25b-11e8-83e3-17744a5411a7.gif)

**Comment by WildStrawberryEVE** [comment] 2018-09-29 12:03
Some of my users also report the problem with type field not being available. It's available when they re-select the wormhole.
Problem seems unrelated to the user agent (both chrome and firefox users reported that).
I could not reproduce that on my computer but 3+ users reported that behaviour to me.

**Comment by ArkusBrightstar** [comment] 2018-09-29 21:41
At 1.20 when the wormhole sig is updated, the type column stays blank, it used to come up with a red "unknown' that you could click on to set the type, at 1.50 i changed the sig to a data site and back to a wormhole, this "fixed" the issue as the type window comes up and allows me to set it as a K162, at 2 mins i am trying to scroll the drop down window with my mouse wheel, it doesnt do this? not sure if that is intentional or not but it would be easier if it did. At 2.35 i paste a gas site in, the type column stays empty. At 4.25 i paste another wormhole sig, this has the same issue as the type column stays empty At 4.37 i select a different worm hole, and reselect the one i am scanning.. this seems to fix the colums as the red "unknown" is in all columns where it should be and i am able to edit them.

**Comment by ArkusBrightstar** [comment] 2018-09-29 21:43
https://i.imgur.com/TjnFCsv.gifv also have a couple of my users reporting the signature updater doesnt paste new signatures, the "update signatures" button doesnt work

**Comment by dnolen** [comment] 2018-09-30 14:05
> Hmmm I can´t reproduce this, we need more details information:
> 
> * Which System  (wormhole, C1, C2,.... , k-space)?
> 
> #### This is what I tried to reproduce:
> 1. Add _random_ system (e.g. J120256 C1 )
> 2. Select system
> 3. Lazy paste a scan result (e.g. Relic signature with unknown type)
> 4. Choose  **type** by **hand** (e.g. Forgotten Perimeter Coronation Platform )
> 5. Re paste same scan result (with **missing** type information)
> 6. Check the "updated" timestamp column of the signature to verify _lazy&update_ worked (even if wie don´t expect any changes to that signature)
> 7. **type** information is still there -> happy :)
> 8. Select system again -> We expect signature with selected **type** information -> happy :)
> 
> ![signature_bug_reproduce_attempt](https://user-images.githubusercontent.com/9299033/46142879-a4a53080-c258-11e8-9204-0f16cc6560a4.gif)


On the first load of the sig list this issue is present, Cannot select the type field or leads to fields. Only the entry type and description fields 

ALso have issues with the pop up for the leads to field jittering when adding a new wormhole system and there are no connectable systems aside from the entry system ID

**Comment by exodus4d** [comment] 2018-10-06 13:05
#### I could hunt down the bug. I´m searching for a proper solution. In fact there are two issues:

It happens if **someone else** "_Client A_" changes the **groupId** of a signature and "_Client B_" gets the updated signature from server and signature table get updated.

**Comment by exodus4d** [comment] 2018-10-06 20:02
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*

**Closed** 2018-10-08 18:09 UTC
Labels: major bug
