### ISSUE TITLE
Get an error when use latest version

### ISSUE THREAD

**Issue by evileyecc1** [exodus4d/pathfinder#632] opened 2018-06-05 00:52 UTC
![qq 20180605085201](https://user-images.githubusercontent.com/22828359/40948899-bb76728e-689d-11e8-819c-a7d89daf2709.png)

**Comment by exodus4d** [comment] 2018-06-07 17:47
I think this issue is a duplicate of #595

could you please linke the full stacktrace? 
Can you link your Session config values from `config.ini`, `CACHE` and `SESSION_CACHE` values?
Which PHP Version?

**Comment by exodus4d** [comment] 2018-06-15 17:42
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #595
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*

**Closed by exodus4d** 2018-06-15 17:42 UTC
Labels: minor bug
