### ISSUE TITLE
login issues 1.4.1

### ISSUE THREAD

**Issue by chiefdan** [exodus4d/pathfinder#718] opened 2018-11-29 00:42 UTC
We are having a login issue where upon return from Eve SSO the character is selected and the user is returned to the character selection screen immediately.

The link is here:

https://[fqdn redacted]/sso/login?cookie=char_88732336c1309d6464fab1d3ae6b8623&tabId=n2j7q

We've cleared cookies client and server side and the issue persists. We are on version 1.4.1.

After waiting some time on the character select screen at some point the map may load.

My background is infrastructure so I'm not able to troubleshoot web very well, but if someone can assist to let me know which logs to maybe look at?

**Comment by Kaoraku** [comment] 2018-12-09 10:40
We have the same issue, with 1.4.3

Also time to time got error 500 with the msg:

> Internal Server Error
> 
> Fatal error: Module 'mbstring' already loaded

**Comment by dmullaney** [comment] 2018-12-14 12:21
I have this problem too - 1.4.3

**Comment by chiefdan** [comment] 2018-12-18 15:08
We've updated to 1.4.3, switched to redis cache and rebuilt a new pathfinder db, the issue persists.

**Comment by TrinityErik** [comment] 2018-12-20 06:56
Also having this problem on 1.4.3

**Comment by TrinityErik** [comment] 2018-12-21 16:37
Any chance this will be looked at soon?  Causing major issues here, it is so bad my guys are giving up on using Pathfinder.

**Comment by chiefdan** [comment] 2018-12-22 00:14
@TrinityErik I've noticed that I don't have the issue on my backup and dev servers, which are running on Ubuntu 18.04, only on the main which is on 16.04. I doubt the OS is responsible but it could be some of the default dependency versions. Looking to rebuild the main on 18.04 and see if it still occurs.

**Comment by exodus4d** [comment] 2018-12-22 11:10
It looks like this issue and the conversation here relates to totally different issues:

@Kaoraku Please check your php.ini file for duplicate entries of the  `mbstring` module. This is a PHP config issue. 

@TrinityErik I saw the same login issues 2 days ago. CCP has a devblog about the issue (https://developers.eveonline.com/blog/article/removal-of-redirect-from-.tech.ccp.is-on-jan-7th) the "old" ESI API URL changed, and they removed the ESI URL `https://esi.tech.ccp.is` (which is configured in your `environment.ini`) and replaced it with the new URL `https://esi.evetech.net`.
There is already an open PR for this which will be merged soon. But you should update the URL in your config, asap: https://github.com/exodus4d/pathfinder/pull/728/commits/fb48111e0207f1984020a133fad8b277a1227816

@chiefdan The next commit includes multiple improvements to the login sequence:
- In case of login errors, users will get more detailed notification about the error type
- In case of login errors, _PHP_ logs more information about the issue into a new log file `/log/character_access.log`
- _ESI_ "access_token" handling is completely re-written. In case an "access_token" expires (max lifetime = 20min), a new token is requested from CCP *2min* before the expire time of the old token reaches. In case of an error response for the new token (e.g. ESI timeouts,...) users will no longer get logged out. _Pathfinder_  tries to request ESI for that new token as long as the old one is still valid (~2min).  In case ESI failed all requests and the old token expires, users get logged out with message.

**Comment by exodus4d** [comment] 2018-12-26 13:12
I was able to reproduce the login issue on my Server! If you see issues where users click at their character image on login page and get redirected to login rather than /map view. You should try this hotfix:

Replace method `checkLogTimer()`: https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/accesscontroller.php#L65

... with this:

``````

**Comment by exodus4d** [comment] 2018-12-26 13:14
#### I was able to reproduce the login issue on my Server! 
If you see issues where users click at their character image on login page and get redirected to login rather than /map view. You should try this hotfix:

Replace method `checkLogTimer()`: https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/accesscontroller.php#L65

... with this:

```
private function checkLogTimer(\Base  $f3, Model\CharacterModel $character){
        $loginCheck = false;

        if(
            !$character->dry() &&
            $character->lastLogin
        ){
            // check logIn time
            $timezone = $f3->get('getTimeZone')();
            $maxLoginMinutes = (int)Config::getPathfinderData('timer.logged');

            $logoutTime  = new \DateTime($character->lastLogin, $timezone);
            $logoutTime->add(new \DateInterval('PT' . $maxLoginMinutes . 'M'));
            $now = new \DateTime('now', $timezone);

            if($logoutTime->getTimestamp() > $now->getTimestamp()){
                $loginCheck = true;
            }
        }

        return $loginCheck;
    }
```

**Comment by chiefdan** [comment] 2018-12-27 01:43
Tested and working for us, many thanks!

**Comment by Slivo-fr** [comment] 2018-12-28 10:03
Any chance to get a minor release with the fix ?

**Closed** 2019-05-11 13:51 UTC
Labels: enhancement, major bug
