### ISSUE TITLE
Internal Error 500, recurrent crash since patch 1.5.2

### ISSUE THREAD

**Issue by Vex035** [exodus4d/pathfinder#818] opened 2019-07-21 08:42 UTC
Hi, first of all i want to thank you for that awesome soft. I just created an account on github to submit this but report. As i dont have a single qualification in programming, i hope that will help you to fix it. Thank you!

●      PATHFINDER console.js:156
● Release: v1.5.2 console.js:186
● Client syncStatus: webSocket. initMapWorker() resolved by command: ws:open! console.js:156
La mémoire consommée par will-change est trop importante. La limite du budget correspond à la surface multipliée par 3 (1332480 px). Les occurrences de will-change dépassant le budget seront ignorées. NDI0NjU=
  ↪ https://www.pathfinder-w.space/api/map/updateUserData Error response: 
(1) […]
​
0: Object { type: "error", code: 500, status: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'A 2232243 ) and ( `target` = 2232243 ) ) or ( ( `source` B 2232243 ) and ( `targ' at line 1 [/var/www/pathfinder-w.space/public_html/app/lib/db/sql.php:226]", … }
​
length: 1
​
<prototype>: Array []
console.js:180
TypeError: e is null
system_signature.js:2446
TypeError: this.eq(...).data(...) is undefined
bootstrap-editable.min.js:5
    editable bootstrap-editable.min.js:5
    getSystemInfo map.js:2829
    g util.js:382
    getDataByConnections util.js:402
    s system_route.js:616
    _ system_route.js:815
    d system_route.js:119
    h system_route.js:196
    jQuery 4
        l
        fireWith
        T
        n

​

**Comment by tralafiti** [comment] 2019-07-21 10:18
Seems to be caused by a missing `operator` on the two first `getFilter` in https://github.com/exodus4d/pathfinder/blob/develop/app/main/model/pathfinder/mapmodel.php#L1313 and the following line

**Comment by Vex035** [comment] 2019-07-21 12:05
It seems to work since DT, but now, for each system i travel trough, it shows (1) pilot inside, even after i leave them.

**Comment by exodus4d** [comment] 2019-07-21 19:59
@Vex035 Thanks for your report. 
My bad, this should be fixed now.

@tralafiti sry, I havn´t seen your PR. This Issue is fixed by https://github.com/exodus4d/pathfinder/commit/c96291432ed0974ad88c56b15c82a2886bb68f14

**Closed by exodus4d** 2019-07-21 19:59 UTC

**Comment by tralafiti** [comment] 2019-07-21 21:04
No problem :-)
